<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ec46bf70-c209-41c2-8ced-021fb41bf72d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArnavutkoyBelediyesi.Application\ArnavutkoyBelediyesi.Application.csproj" />
    <ProjectReference Include="..\ArnavutkoyBelediyesi.Infrastructure\ArnavutkoyBelediyesi.Infrastructure.csproj" />
    <ProjectReference Include="..\ArnavutkoyBelediyesi.Persistence\ArnavutkoyBelediyesi.Persistence.csproj" />
  </ItemGroup>

</Project>
